name: 'Auto Versioning'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - name: Get latest tag
      id: latest_tag
      run: |
        PREFIX='v'
        VERSION_NUM='[0-999]' 
        LATEST_TAG=$(git tag --list "${PREFIX}${VERSION_NUM}\.${VERSION_NUM}" --sort=-version:refname | head -n 1)
        echo "$LASTEST_TAG"
        
        echo "$LASTEST_TAG"
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
    - name: New tag minor
      id: new_tag_minor
      if: github.event_name == 'push' && github.ref != 'refs/heads/main'
      run: |
        NEW_TAG=$(echo $LATEST_TAG | awk -F. '{$1 = $1; $2 = $2 + 1;} 1' OFS=.)
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "$NEW_TAG"
    - name: New tag major
      id: new_tag_major
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        NEW_TAG=$(echo $LATEST_TAG | awk -F. '{$1 = $1 + 1; $2 = 0;} 1' OFS=.)
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "$NEW_TAG"
    - name: Push Git Tag  
      run: |
        NEW_TAG=${{ env.NEW_TAG }}
        NEW_TAG="v$NEW_TAG"
        git tag $NEW_TAG
        git push origin $NEW_TAG
