name: 'Auto Versioning'
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - name: Get latest tag
      id: latest_tag
      run: |
        LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "Latest tag label is $LATEST_TAG"
        echo "::set-output name=tag_label::$LATEST_TAG"