name: 'Auto Versioning'
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get latest tag
      id: latest_tag
      run: |
        LATEST_TAG=$(git describe --tags)
        echo "Latest tag label is $LATEST_TAG"
        echo "::set-output name=tag_label::$LATEST_TAG"